#!/usr/bin/env python3

import pandas as pd
import os
import pickle
from tqdm import tqdm

all_files = os.listdir()
files = []
for file in all_files:
    if file.endswith('.csv'):
        files.append(file)

n = -1
for file in tqdm(files):
    cols = pd.read_csv(file, index_col=0, nrows=0).columns.tolist()
    if 'TMAX' in cols:
        try:
            df1 = pd.read_csv(file,dtype='str',engine='python',
                              usecols = ['DATE','LATITUDE','LONGITUDE','TMAX'],
                              error_bad_lines=False)
            yr1 = int(df1['DATE'][0][:4])
            yr2 = int(df1['DATE'][df1.shape[0]-1][:4])
            if yr1 <= 1991 and yr2 == 2021:
                n += 1
                if n == 0:
                    df = df1.copy()
                else:
                    df = pd.concat([df,df1])
            else:
                continue
        except pd.errors.ParserError:
            df1 = pd.read_csv(file,dtype='str',engine='c',
                              usecols = ['DATE','LATITUDE','LONGITUDE','TMAX'],
                              error_bad_lines=False)
            yr1 = int(df1['DATE'][0][:4])
            yr2 = int(df1['DATE'][df1.shape[0]-1][:4])
            if yr1 <= 1991 and yr2 == 2021:
                n += 1
                if n == 0:
                    df = df1.copy()
                else:
                    df = pd.concat([df,df1])
            else:
                continue
    else:
        continue

f = open("all_stations.pkl","wb")
pickle.dump(df,f)
f.close()
